import { Question } from '@/types/questions';

export const questions: Question[] = [
  {
    id: '1',
    type: 'multiple-choice',
    text: "Which airline is Gatwick's largest operator?",
    options: ["EasyJet", "British Airways", "Emirates", "Ryanair"],
    correct_answer: "EasyJet",
    timeLimit: 8,
  },
  {
    id: '2',
    type: 'multiple-choice',
    text: "Which airport has the IATA airport code BHD?",
    options: ["Bangkok", "Belfast City", "Berlin", "Bordeaux"],
    correct_answer: "Belfast City",
    timeLimit: 8,
  },
  {
    id: '3',
    type: 'wordsearch',
    text: "Find airport-related words",
    grid: [
      ['G', 'A', 'T', 'E', 'Y'],
      ['R', 'U', 'N', 'W', 'A'],
      ['P', 'I', 'L', 'O', 'T'],
      ['J', 'E', 'T', 'S', 'K'],
      ['B', 'A', 'G', 'S', 'Z'],
    ],
    validWords: ["GATE", "RUNWAY", "PILOT", "JETS", "BAGS"],
    timeLimit: 40,
  },
  {
    id: '4',
    type: 'multiple-choice',
    text: "Which airline's Premium Economy offers plant-powered plates including Kimchi Fried Rice with roasted pumpkin and sautéed oyster mushrooms?",
    options: ["British Airways", "Emirates", "Singapore Airlines", "Uganda Airlines"],
    correct_answer: "Emirates",
    timeLimit: 10,
  },
  {
    id: '5',
    type: 'ordering',
    text: "Order these by passenger capacity (smallest to largest)",
    items: ["Regional Jet", "A320", "Boeing 777", "A380"],
    correctOrder: ["Regional Jet", "A320", "Boeing 777", "A380"],
    timeLimit: 20,
  },
  {
    id: '6',
    type: 'multiple-choice',
    text: "Which is the shortest flight running from London Gatwick?",
    options: ["Amsterdam", "Dublin", "Jersey", "Paris"],
    correct_answer: "Jersey",
    timeLimit: 8,
  },
  {
    id: '7',
    type: 'connection',
    text: "Find the 4 related words",
    items: ["Boots", "Boss", "Trousers", "West", "Hamleys", "Sunglasses", "Lego", "Luton"],
    correctItems: ["Boots", "Boss", "Hamleys", "Lego"],
    connectionHint: "Gatwick's North Terminal shopping options",
    timeLimit: 30,
  },
  {
    id: '8',
    type: 'multiple-choice',
    text: "Which airline operated its first commercial flight from London Gatwick in June 1984?",
    options: ["easyJet", "Jet2.com", "Tui", "Virgin Atlantic"],
    correct_answer: "Virgin Atlantic",
    timeLimit: 8,
  },
  {
    id: '9',
    type: "wordsearch",
    text: "Find security checkpoint word",
    grid: [
      ['B', 'P', 'L', 'I', 'B'],
      ['S', 'C', 'O', 'P', 'E'],
      ['T', 'R', 'A', 'Y', 'L'],
      ['L', 'A', 'N', 'E', 'T'],
      ['B', 'O', 'O', 'T', 'P'],
    ],
    validWords: ["BELT", "SCAN", "TRAY", "LANE", "BOOTS"],
    timeLimit: 40
  },
  {
    id: '10',
    type: 'multiple-choice',
    text: "Where at London Gatwick could you try the cult hit Green Burger?",
    options: ["The Red Lion (J.D. Wetherspoon)", "Shake Shack", "Emirates Lounge", "Krispy Kreme"],
    correct_answer: "Emirates Lounge",
    timeLimit: 12,
  },
  {
    id: '11',
    type: 'ordering',
    text: "Order the departure process (first to last)",
    items: ["Security", "Check-in", "Boarding", "Take-off"],
    correctOrder: ["Check-in", "Security", "Boarding", "Take-off"],
    timeLimit: 20,
  },
  {
    id: '12',
    type: 'multiple-choice',
    text: "In which UK county is London Gatwick Airport primarily located?",
    options: ["Surrey", "Kent", "West Sussex", "Hampshire"],
    correct_answer: "West Sussex",
    timeLimit: 8,
  },
  {
    id: '13',
    type: 'ordering',
    text: "Order these by typical altitude (lowest to highest)",
    items: ["Cruising Altitude", "Helicopter", "Drone", "Clouds"],
    correctOrder: ["Drone", "Helicopter", "Clouds", "Cruising Altitude"],
    timeLimit: 25,
  },
  {
    id: '14',
    type: 'connection',
    text: "Find the 4 related words",
    items: ["Heathrow", "Stansted", "London City", "Southend", "Manchester", "Bristol", "Glasgow", "Dublin"],
    correctItems: ["Heathrow", "Stansted", "London City", "Southend"],
    connectionHint: "The other airports serving the London area",
    timeLimit: 25,
  },
  {
    id: '15',
    type: 'ordering',
    text: "Order these plane parts from nose to tail",
    items: ["Wing", "Cockpit", "Galley", "Tail"],
    correctOrder: ["Cockpit", "Wing", "Galley", "Tail"],
    timeLimit: 20,
  },
  {
    id: '16',
    type: 'multiple-choice',
    text: "Which airline's cabin crew wear a sarong kebaya?",
    options: ["Azerbaijan Airlines", "Ethiopian Airlines", "Singapore Airlines", "Turkish Airlines"],
    correct_answer: "Singapore Airlines",
    timeLimit: 8,
  },
  {
    id: '17',
    type: 'ordering',
    text: "Order these by top speed (slowest to fastest)",
    items: ["Baggage Tug", "Truck", "Boeing 747", "Concorde"],
    correctOrder: ["Baggage Tug", "Truck", "Boeing 747", "Concorde"],
    timeLimit: 25
  },
  {
    id: '18',
    type: 'connection',
    text: "Find the 4 related words",
    items: ["Gates", "Arrivals", "Bottle", "Mouse", "Toilets", "Baggage", "Hotel", "Travel"],
    correctItems: ["Gates", "Arrivals", "Toilets", "Baggage"],
    connectionHint: "Standard icons on airport signs",
    timeLimit: 30,
  },
  {
    id: '19',
    type: 'multiple-choice',
    text: "Which airline scores highest for sustainability in 2026?",
    options: ["British Airways", "easyJet", "Ryanair", "Tui"],
    correct_answer: "British Airways",
    timeLimit: 8,
  },
  {
    id: '20',
    type: 'connection',
    text: "Find the 4 related words",
    items: ["Perfume", "Apple", "Lotion", "Shampoo", "Toothpaste", "Vodka", "Petrol", "Laptop"],
    correctItems: ["Perfume", "Lotion", "Shampoo", "Toothpaste"],
    connectionHint: "Toiletries allowed in a 100ml clear bag",
    timeLimit: 25,
  },
  {
    id: '21',
    type: 'multiple-choice',
    text: "Which of these terminals at Gatwick is connected to the train station by a 2-minute automated shuttle?",
    options: ["North Terminal", "South Terminal", "East Terminal", "West Terminal"],
    correct_answer: "North Terminal",
    timeLimit: 8,
  },
  {
    id: '22',
    type: 'connection',
    text: "Find the 4 related words",
    items: ["Altimeter", "Clutch", "Compass", "Airspeed", "Laptop", "Pedals", "Radar", "Windows"],
    correctItems: ["Altimeter", "Compass", "Airspeed", "Radar"],
    connectionHint: "Primary flight instruments",
    timeLimit: 25
  },
  {
    id: '23',
    type: 'multiple-choice',
    text: "What is the name of the original circular terminal building at Gatwick, which opened in 1936?",
    options: ["The Hub", "The Roundhouse", "The Beehive", "The Orbit"],
    correct_answer: "The Beehive",
    timeLimit: 10,
  },
  {
    id: '24',
    type: 'ordering',
    text: "Order the standard flight departure sequence (first to last)",
    items: ["Pushback", "Taxi", "Take-off", "Initial Climb"],
    correctOrder: ["Pushback", "Taxi", "Take-off", "Initial Climb"],
    timeLimit: 20,
  },
  {
    id: '25',
    type: 'wordsearch',
    text: "Find airlines (2 letters or longer)",
    grid: [
      ['E', 'A', 'S', 'Y', 'P'],
      ['T', 'U', 'I', 'L', 'A'],
      ['B', 'A', 'B', 'O', 'S'],
      ['N', 'O', 'R', 'S', 'E'],
      ['W', 'I', 'N', 'G', 'S'],
    ],
    validWords: ["EASY", "TUI", "BA", "NORSE", "WINGS"],
    timeLimit: 40,
  }
];