import { Question } from '@/types/questions';

export const questions: Question[] = [
  {
    id: '1',
    type: 'multiple-choice',
    text: "Which airline is Gatwick's largest operator?",
    options: ["EasyJet", "British Airways", "Emirates", "Ryanair"],
    correct_answer: "EasyJet",
    timeLimit: 8,
  },
  {
    id: '2',
    type: 'multiple-choice',
    text: "Which airline scores highest for sustainability in 2026?",
    options: ["British Airways", "easyJet", "Ryanair", "Tui"],
    correct_answer: "British Airways",
    timeLimit: 8,
  },
  {
    id: '3',
    type: 'multiple-choice',
    text: "Which airport has the IATA airport code BHD?",
    options: ["Bangkok", "Belfast City", "Berlin", "Bordeaux"],
    correct_answer: "Belfast City",
    timeLimit: 8,
  },
  {
    id: '4',
    type: 'wordsearch',
    text: "Find airport-related words",
    grid: [
      ['G', 'A', 'T', 'E', 'Y'],
      ['R', 'U', 'N', 'W', 'A'],
      ['P', 'I', 'L', 'O', 'T'],
      ['J', 'E', 'T', 'S', 'K'],
      ['B', 'A', 'G', 'S', 'Z'],
    ],
    validWords: ["GATE", "RUNWAY", "PILOT", "JETS", "BAGS"],
    timeLimit: 40,
  },
  {
    id: '5',
    type: 'multiple-choice',
    text: "Which airline's Premium Economy offers plant-powered plates including Kimchi Fried Rice with roasted pumpkin and sautéed oyster mushrooms?",
    options: ["British Airways", "Emirates", "Singapore Airlines", "Uganda Airlines"],
    correct_answer: "Emirates",
    timeLimit: 10,
  },
  {
    id: '6',
    type: 'ordering',
    text: "Order these by passenger capacity (smallest to largest)",
    items: ["Regional Jet", "A320", "Boeing 777", "A380"],
    correctOrder: ["Regional Jet", "A320", "Boeing 777", "A380"],
    timeLimit: 20,
  },
  {
    id: '7',
    type: 'multiple-choice',
    text: "Which is the shortest flight running from London Gatwick?",
    options: ["Amsterdam", "Dublin", "Jersey", "Paris"],
    correct_answer: "Jersey",
    timeLimit: 8,
  },
  {
    id: '8',
    type: 'connection',
    text: "Find the 4 related words",
    items: ["Boots", "Boss", "Trousers", "West", "Hamleys", "Sunglasses", "Lego", "Luton"],
    correctItems: ["Boots", "Boss", "Hamleys", "Lego"],
    connectionHint: "Gatwick's North Terminal shopping options",
    timeLimit: 30,
  },
  {
    id: '9',
    type: 'multiple-choice',
    text: "Which airline operated its first commercial flight from London Gatwick in June 1984?",
    options: ["easyJet", "Jet2.com", "Tui", "Virgin Atlantic"],
    correct_answer: "Virgin Atlantic",
    timeLimit: 8,
  },
  {
    id: '10',
    type: 'multiple-choice',
    text: "Which airline's cabin crew wear a sarong kebaya?",
    options: ["Azerbaijan Airlines", "Ethiopian Airlines", "Singapore Airlines", "Turkish Airlines"],
    correct_answer: "Singapore Airlines",
    timeLimit: 8,
  },

];